language: node_js
node_js:
- '8'
cache: npm
branchs: 
  only:
  - master
sudo: true
notifications:
  email: false
install:
- npm install
script: true
addons:
  ssh_known_hosts:
  - 107.182.188.188:12306
before_install:
- openssl aes-256-cbc -K $encrypted_7e7570131d4e_key -iv $encrypted_7e7570131d4e_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh root@107.182.188.188 -p 12306 -o StrictHostKeyChecking=no "cd /var/ftp/public_root/blog-fe/blog/ && git pull origin master && npm run build && rm -rf /var/ftp/public_root/blog/dist && cp -r /var/ftp/public_root/blog-fe/blog/dist /var/ftp/public_root/blog/dist && pm2 restart app"
# - chmod +x deploy.sh
