language: node_js
node_js:
- '8'
branchs:
  only:
  - master
sudo: true
notifications:
  email: false
# install:
#   - yarn cache clean
#   - yarn install
script: true
addons:
  ssh_known_hosts:
  - 107.182.188.188:12306
before_install:
# - npm install -g yarn --cache-min 999999999
- openssl aes-256-cbc -K $encrypted_a5923803cb6d_key -iv $encrypted_a5923803cb6d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh root@107.182.188.188 -p 12306 -o StrictHostKeyChecking=no "cd /var/ftp/public_root/blog-fe/blog-ts/
  && git pull origin master
  && cnpm install
  && cnpm run build
  && cp -r /var/ftp/public_root/blog-fe/blog-ts/build /var/ftp/public_root/blog/dist
  && cp -r /var/ftp/public_root/blog-fe/blog-ts/server /var/ftp/public_root/blog/server
  && cd /var/ftp/public_root/blog/server
  && cnpm install
  && tsc
  && pm2 start ./dist/server/app"