export default {
    ADD_EDITOR: "ADD_EDITOR",
    GET_ALL_LIST: "GET_ALL_LIST",
    GET_ARTICLE_BY_ID: "GET_ARTICLE_BY_ID",
    GET_TAG_LIST: "GET_TAG_LIST",
    LOGIN: "LOGIN",
    SAVE_USER_INFO: "SAVE_USER_INFO",
    SHOW_DELETE: "SHOW_DELETE",
    SHOW_LOGIN: "SHOW_LOGIN"
};